### PR TITLE
Fix `gigimport` in RSA

### LINKED ISSUE #9: Wrong giant.sign from gigimport
https://github.com/XboxDev/xbedump/blob/d0d6508db7a4e5fcf159dab40853c695b4c52e6e/giants.c#L320-L335

Does not work if `w` is zero at start of loop (in trivial values like `0000 0001`).

`w&c` will never be true, so the loop never exits.

At first I thought the correct condition would probably be  `c && (w&c)` so it counts.

---

However, the function is weird to begin with:

```0000 0000``` = len 0 (`n` is zero: special case)
```0001 0000``` = len 17 ('w' is 1 bit, `sign` is 2 &rarr; 1 * 16 bit)
```0000 0001``` = len 16 (`w` is 0 bit, but `sign` is 2 &rarr; 1 * 16 bit); but why isn't this 1?

I wonder if this has to do with the removal in #5 (see #4 for a poor description of this).

From what I can tell, it didn't make sense to have numbers with zero-words in the top words (you'd just decrement `sign` instead).

---

So I also looked for where the code came from, and found https://github.com/rudimeier/mprime/blob/master/gwnum/giants.c which is a 32 bit port. It also has an assert for `g->n[abs(g->sign)-1] != 0` which warns about `w` being zero.

So we should:

- Fix our gigimport and add the license text.
- Consider an upgrade to the 32 bit (or even 64 bit) lib and add the license text.
- Consider switching to an entirely different RSA implementation.

The same bugs also plague @Cxbx-Reloaded which uses the same giants.c in its EmuRSA.cpp (which is also a copyright violation: it doesn't contain the copyright strings, which are mandatory according to the license)

### LINKED ISSUE #10: Segmentation fault on NXDK Xbe's
I get a segmentation fault when trying to xbedump an NXDK xbe.

I tried the following:
```bash
xbedump default.xbe -dh
```
the result is:
```
Segmentation fault
```
`default.xbe` is the compiled version of [sdl2-tetris-xbox](https://github.com/chrisderwahre/sdl2-tetris-xbox)

i tried to run it through gdb using `gdb --args xbedump default.xbe -dh `
result: 
```
(gdb) r
Starting program: C:\Users\Chris\msys2\usr\bin\xbedump.exe default.xbe -dh
[New Thread 6052.0x152c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004015ab in popg() ()
```

```
(gdb) bt
#0  0x00000000004015ab in popg() ()
#1  0x00000000004044a8 in karatsquareg(giantstruct*) ()
#2  0x000000000040455d in karatsquareg(giantstruct*) ()
``` 
and then `#2` repeats itself a few thousand times

Here are the results from xbedump compiled with debug symbols:
```
(gdb) r
Starting program: C:\Users\Chris\msys2\usr\bin\xbedump.exe default.xbe -dh
[New Thread 8468.0x2898]

Thread 1 received signal SIGSEGV, Segmentation fault.
popg () at giants.c:263
263             stack[cur_stack_elem]->sign = 0;
```
```
(gdb) bt
#0  popg () at giants.c:263
#1  0x0000000000405452 in karatsquareg (x=0x6e18ad040) at giants.c:2563
#2  0x00000000004054d1 in karatsquareg (x=0x6e1577040) at giants.c:2568
```
`#2` again, repeats a few hundred times, but `x` is incremented.

### PR DESCRIPTION
**Pull request by JayFoxRox**
Backport of changes that were done in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1561

Additionally, an assert was removed because it warns about (what appears to be) a valid state. See this discussion on this PR: https://github.com/XboxDev/xbedump/pull/11#discussion_r291654891

Hopefully closes #9 and hopefully closes #10

### CODE REVIEW

File: xboxlib.c [hunk 1]
```diff
@@ -184,15 +184,21 @@ int read_rsafrombin_asterix()
...
 
+	// Get number of shorts
 	g->sign = len / 2;
 
+	// Only count used shorts
+	while((g->sign >= 1) && (g->n[g->sign - 1] == 0)) {
+		g->sign -= 1;
+	}
+
 	assert(g->sign != 0);
```
Comment (JayFoxRox) [inline xboxlib.c]: This assert gets triggered for nxdk XBEs now, because `buff` is `len` bytes of zero.

I'm not sure why this check exists in the first place?

Comment (JayFoxRox) [reply xboxlib.c]: This seems to be a hack that was introduced here: https://github.com/XboxDev/xbedump/commit/dd703113878c8ae814c71c99aee3af640447c619#diff-e64a6c66ddd61d0fa1f0670ca3423da2L227

---

I don't think the additional check / fixup for `g->sign == 0` isn't even necessary, because https://github.com/XboxDev/xbedump/blob/d0d6508db7a4e5fcf159dab40853c695b4c52e6e/giants.c#L359-L377 also checks if the length is zero. So `g->sign == 0` appears to be a valid state.

It also handles 0 like that in this:

https://github.com/XboxDev/xbedump/blob/d0d6508db7a4e5fcf159dab40853c695b4c52e6e/giants.c#L393-L407

Comment (JayFoxRox) [reply xboxlib.c]: I've removed this assert.

**Comment by chrisderwahre** [comment]
I tested this PR on the following:
- 2 Retail Games [XDK Binaries]
 - 2 NXDK Binaries

All worked just fine after this change.
Before these changes, NXDK binaries would seg fault. [As this PR also says that it fixes #10 ]

**Comment by GXTX** [comment]
Tested using the `hello` sample from `nxdk` and can confirm it does work as expected. Hopefully we can get another maintainer to verify and merge, thanks.
